# Generated by Django 6.1 on 2026-08-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=30)),
                ('crop_age', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
                ('disease_img_1', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('disease_img_2', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('disease_img_3', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('disease_img_4', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('disease', models.TextField(blank=True, default=None)),
            ],
        ),
    ]
