# Generated by Django 6.1 on 2026-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_details',
            name='crop_age',
            field=models.PositiveIntegerField(),
        ),
    ]
