# Generated by Django 6.1 on 2026-08-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arg_app', '0002_alter_crop_details_crop_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_details',
            name='crop_age',
            field=models.CharField(max_length=50),
        ),
    ]
