# Generated by Django 6.1 on 2026-10-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arg_app', '0003_alter_crop_details_crop_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=50)),
                ('soil_ph', models.CharField(max_length=50)),
                ('organic_carbon', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=10)),
                ('Fram_area', models.CharField(max_length=50)),
                ('irragation_type', models.CharField(max_length=50)),
                ('water_scource', models.CharField(max_length=50)),
                ('planting_date', models.CharField(max_length=50)),
                ('pervious_crop', models.CharField(max_length=50)),
                ('Desired_Crop', models.CharField(max_length=50)),
            ],
        ),
    ]
